### ISSUE TITLE
About `encoder_bn_train` in `class ReContrast(nn.Module)`

### ISSUE THREAD

**Issue by caiyu6666** [guojiajeremy/ReContrast#3]
Thanks for your great work. I have a question about `model.train(encoder_bn_train=True)`.

It is set `True` for some datasets, while `False` for OCT2017 and etc. I am wondering the reason why you choose this setting. Or whether it is chosen empirically?

**Comment by guojiajeremy** [comment]
To be brief, it is chosen empirically. 
On some datasets, setting BN mode to train is unstable during training or yields suboptimal performance. This phenomenon (and possible reasons) is discussed in the Appendix of our paper. In addition, we tried some tricks that make it possible to set all BN to _train_ uniformly (see Stable Training in Readme and the Appendix). However, it is still a little better to choose BN mode empirically.

**Comment by caiyu6666** [comment]
Got it. Thanks!
